//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace CrmEarlyBound.OptionSet {
  [System.Runtime.Serialization.DataContractAttribute()]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "8.2.1.8676")]
  public enum ComponentState
  {

    [System.Runtime.Serialization.EnumMemberAttribute()]
    Deleted = 2,

    [System.Runtime.Serialization.EnumMemberAttribute()]
    DeletedUnpublished = 3,

    [System.Runtime.Serialization.EnumMemberAttribute()]
    Published = 0,

    [System.Runtime.Serialization.EnumMemberAttribute()]
    Unpublished = 1,
  }

  [System.Runtime.Serialization.DataContractAttribute()]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "8.2.1.8676")]
  public enum SystemUser_AccessMode
  {

    [System.Runtime.Serialization.EnumMemberAttribute()]
    Administrative = 1,

    [System.Runtime.Serialization.EnumMemberAttribute()]
    DelegatedAdmin = 5,

    [System.Runtime.Serialization.EnumMemberAttribute()]
    Noninteractive = 4,

    [System.Runtime.Serialization.EnumMemberAttribute()]
    Read = 2,

    [System.Runtime.Serialization.EnumMemberAttribute()]
    ReadWrite = 0,

    [System.Runtime.Serialization.EnumMemberAttribute()]
    SupportUser = 3,
  }

  [System.Runtime.Serialization.DataContractAttribute()]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "8.2.1.8676")]
  public enum SystemUser_Address1_AddressTypeCode
  {

    [System.Runtime.Serialization.EnumMemberAttribute()]
    DefaultValue = 1,
  }

  [System.Runtime.Serialization.DataContractAttribute()]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "8.2.1.8676")]
  public enum SystemUser_Address1_ShippingMethodCode
  {

    [System.Runtime.Serialization.EnumMemberAttribute()]
    DefaultValue = 1,
  }

  [System.Runtime.Serialization.DataContractAttribute()]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "8.2.1.8676")]
  public enum SystemUser_Address2_AddressTypeCode
  {

    [System.Runtime.Serialization.EnumMemberAttribute()]
    DefaultValue = 1,
  }

  [System.Runtime.Serialization.DataContractAttribute()]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "8.2.1.8676")]
  public enum SystemUser_Address2_ShippingMethodCode
  {

    [System.Runtime.Serialization.EnumMemberAttribute()]
    DefaultValue = 1,
  }

  [System.Runtime.Serialization.DataContractAttribute()]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "8.2.1.8676")]
  public enum SystemUser_CALType
  {

    [System.Runtime.Serialization.EnumMemberAttribute()]
    Administrative = 1,

    [System.Runtime.Serialization.EnumMemberAttribute()]
    Basic = 2,

    [System.Runtime.Serialization.EnumMemberAttribute()]
    DeviceBasic = 4,

    [System.Runtime.Serialization.EnumMemberAttribute()]
    DeviceEnterprise = 8,

    [System.Runtime.Serialization.EnumMemberAttribute()]
    DeviceEssential = 6,

    [System.Runtime.Serialization.EnumMemberAttribute()]
    DeviceProfessional = 3,

    [System.Runtime.Serialization.EnumMemberAttribute()]
    Enterprise = 7,

    [System.Runtime.Serialization.EnumMemberAttribute()]
    Essential = 5,

    [System.Runtime.Serialization.EnumMemberAttribute()]
    FieldService = 11,

    [System.Runtime.Serialization.EnumMemberAttribute()]
    Professional = 0,

    [System.Runtime.Serialization.EnumMemberAttribute()]
    ProjectService = 12,

    [System.Runtime.Serialization.EnumMemberAttribute()]
    Sales = 9,

    [System.Runtime.Serialization.EnumMemberAttribute()]
    Service = 10,
  }

  [System.Runtime.Serialization.DataContractAttribute()]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "8.2.1.8676")]
  public enum SystemUser_EmailRouterAccessApproval
  {

    [System.Runtime.Serialization.EnumMemberAttribute()]
    Approved = 1,

    [System.Runtime.Serialization.EnumMemberAttribute()]
    Empty = 0,

    [System.Runtime.Serialization.EnumMemberAttribute()]
    PendingApproval = 2,

    [System.Runtime.Serialization.EnumMemberAttribute()]
    Rejected = 3,
  }

  [System.Runtime.Serialization.DataContractAttribute()]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "8.2.1.8676")]
  public enum SystemUser_IncomingEmailDeliveryMethod
  {

    [System.Runtime.Serialization.EnumMemberAttribute()]
    ForwardMailbox = 3,

    [System.Runtime.Serialization.EnumMemberAttribute()]
    MicrosoftDynamics365forOutlook = 1,

    [System.Runtime.Serialization.EnumMemberAttribute()]
    None = 0,

    [System.Runtime.Serialization.EnumMemberAttribute()]
    ServerSideSynchronizationorEmailRouter = 2,
  }

  [System.Runtime.Serialization.DataContractAttribute()]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "8.2.1.8676")]
  public enum SystemUser_InviteStatusCode
  {

    [System.Runtime.Serialization.EnumMemberAttribute()]
    InvitationAccepted = 4,

    [System.Runtime.Serialization.EnumMemberAttribute()]
    InvitationExpired = 3,

    [System.Runtime.Serialization.EnumMemberAttribute()]
    InvitationNearExpired = 2,

    [System.Runtime.Serialization.EnumMemberAttribute()]
    InvitationNotSent = 0,

    [System.Runtime.Serialization.EnumMemberAttribute()]
    InvitationRejected = 5,

    [System.Runtime.Serialization.EnumMemberAttribute()]
    InvitationRevoked = 6,

    [System.Runtime.Serialization.EnumMemberAttribute()]
    Invited = 1,
  }

  [System.Runtime.Serialization.DataContractAttribute()]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "8.2.1.8676")]
  public enum SystemUser_OutgoingEmailDeliveryMethod
  {

    [System.Runtime.Serialization.EnumMemberAttribute()]
    MicrosoftDynamics365forOutlook = 1,

    [System.Runtime.Serialization.EnumMemberAttribute()]
    None = 0,

    [System.Runtime.Serialization.EnumMemberAttribute()]
    ServerSideSynchronizationorEmailRouter = 2,
  }

  [System.Runtime.Serialization.DataContractAttribute()]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "8.2.1.8676")]
  public enum SystemUser_PreferredAddressCode
  {

    [System.Runtime.Serialization.EnumMemberAttribute()]
    MailingAddress = 1,

    [System.Runtime.Serialization.EnumMemberAttribute()]
    OtherAddress = 2,
  }

  [System.Runtime.Serialization.DataContractAttribute()]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "8.2.1.8676")]
  public enum SystemUser_PreferredEmailCode
  {

    [System.Runtime.Serialization.EnumMemberAttribute()]
    DefaultValue = 1,
  }

  [System.Runtime.Serialization.DataContractAttribute()]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "8.2.1.8676")]
  public enum SystemUser_PreferredPhoneCode
  {

    [System.Runtime.Serialization.EnumMemberAttribute()]
    HomePhone = 3,

    [System.Runtime.Serialization.EnumMemberAttribute()]
    MainPhone = 1,

    [System.Runtime.Serialization.EnumMemberAttribute()]
    MobilePhone = 4,

    [System.Runtime.Serialization.EnumMemberAttribute()]
    OtherPhone = 2,
  }


  [System.Runtime.Serialization.DataContractAttribute()]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "8.2.1.8676")]
  public enum Workflow_BusinessProcessType
  {

    [System.Runtime.Serialization.EnumMemberAttribute()]
    BusinessFlow = 0,

    [System.Runtime.Serialization.EnumMemberAttribute()]
    TaskFlow = 1,
  }

  [System.Runtime.Serialization.DataContractAttribute()]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "8.2.1.8676")]
  public enum Workflow_Category
  {

    [System.Runtime.Serialization.EnumMemberAttribute()]
    Action = 3,

    [System.Runtime.Serialization.EnumMemberAttribute()]
    BusinessProcessFlow = 4,

    [System.Runtime.Serialization.EnumMemberAttribute()]
    BusinessRule = 2,

    [System.Runtime.Serialization.EnumMemberAttribute()]
    Dialog = 1,

    [System.Runtime.Serialization.EnumMemberAttribute()]
    Workflow = 0,
  }

  [System.Runtime.Serialization.DataContractAttribute()]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "8.2.1.8676")]
  public enum Workflow_Mode
  {

    [System.Runtime.Serialization.EnumMemberAttribute()]
    Background = 0,

    [System.Runtime.Serialization.EnumMemberAttribute()]
    Realtime = 1,
  }

  [System.Runtime.Serialization.DataContractAttribute()]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "8.2.1.8676")]
  public enum Workflow_RunAs
  {

    [System.Runtime.Serialization.EnumMemberAttribute()]
    CallingUser = 1,

    [System.Runtime.Serialization.EnumMemberAttribute()]
    Owner = 0,
  }

  [System.Runtime.Serialization.DataContractAttribute()]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "8.2.1.8676")]
  public enum Workflow_Scope
  {

    [System.Runtime.Serialization.EnumMemberAttribute()]
    BusinessUnit = 2,

    [System.Runtime.Serialization.EnumMemberAttribute()]
    Organization = 4,

    [System.Runtime.Serialization.EnumMemberAttribute()]
    ParentChildBusinessUnits = 3,

    [System.Runtime.Serialization.EnumMemberAttribute()]
    User = 1,
  }

  [System.Runtime.Serialization.DataContractAttribute()]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "8.2.1.8676")]
  public enum Workflow_Stage
  {

    [System.Runtime.Serialization.EnumMemberAttribute()]
    Postoperation = 40,

    [System.Runtime.Serialization.EnumMemberAttribute()]
    Preoperation = 20,
  }

  [System.Runtime.Serialization.DataContractAttribute()]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "8.2.1.8676")]
  public enum Workflow_StatusCode
  {

    [System.Runtime.Serialization.EnumMemberAttribute()]
    Activated = 2,

    [System.Runtime.Serialization.EnumMemberAttribute()]
    Draft = 1,
  }

  [System.Runtime.Serialization.DataContractAttribute()]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "8.2.1.8676")]
  public enum Workflow_Type
  {

    [System.Runtime.Serialization.EnumMemberAttribute()]
    Activation = 2,

    [System.Runtime.Serialization.EnumMemberAttribute()]
    Definition = 1,

    [System.Runtime.Serialization.EnumMemberAttribute()]
    Template = 3,
  }

  [System.Runtime.Serialization.DataContractAttribute()]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "8.2.1.8676")]
  public enum Processstage_Category
  {

    [System.Runtime.Serialization.EnumMemberAttribute()]
    Approval = 7,

    [System.Runtime.Serialization.EnumMemberAttribute()]
    Close = 3,

    [System.Runtime.Serialization.EnumMemberAttribute()]
    Develop = 1,

    [System.Runtime.Serialization.EnumMemberAttribute()]
    Identify = 4,

    [System.Runtime.Serialization.EnumMemberAttribute()]
    Propose = 2,

    [System.Runtime.Serialization.EnumMemberAttribute()]
    Qualify = 0,

    [System.Runtime.Serialization.EnumMemberAttribute()]
    Research = 5,

    [System.Runtime.Serialization.EnumMemberAttribute()]
    Resolve = 6,
  }
}